apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: azure-broker
spec:
  url: https://azure-broker.lava-bolt.sapi.cf-app.com
  insecureSkipTLSVerify: true
  authInfo:
    basic:
      secretRef:
        namespace: default
        name: azure-broker-secret
