apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "worker-app"
  namespace: "default"
  labels:
    app: "worker-app"
spec:
  selector:
    matchLabels:
      app: "worker-app"
  template:
    metadata:
      labels:
        app: "worker-app"
    spec:
      volumes:
        - name: service-account
          secret:
           secretName: subscriber-binding
      containers:
        - name: "worker-app"
          image: "servicesapi/worker-app"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: service-account
              mountPath: /var/secrets/service-account
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/service-account/privateKeyData
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  name: subscriber-binding
                  key: projectId
            - name: PUBSUB_SUBSCRIPTION
              valueFrom:
                secretKeyRef:
                  name: subscriber-binding
                  key: subscriptionId
            - name: POSTGRESQL_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql-binding
                  key: uri
            - name: VISION_URL
              valueFrom:
                secretKeyRef:
                  name: vision-binding
                  key: url
            - name: VISION_APIKEY
              valueFrom:
                secretKeyRef:
                  name: vision-binding
                  key: apikey
